export const SET_DATE = 'SET_DATE';
export const SET_DATE_PICKER_VISIBILITY = 'SET_DATE_PICKER_VISIBILITY';
export const SET_STRATEGY_SELECTOR_VISIBILITY =
  'SET_STRATEGY_SELECTOR_VISIBILITY';
export const SET_STRATEGIES_USED = 'SET_STRATEGIES_USED';
export const SET_TRADE_TYPE = 'SET_TRADE_TYPE';
export const SET_TRADE = 'SET_TRADE';
export const SET_PNL = 'SET_PNL';
export const SET_PNL_PERC = 'SET_PNL_PERC';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_BOOKMARK_STATUS = 'SET_BOOKMARK_STATUS';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_SNAPSHOT_UUID = 'SET_SNAPSHOT_UUID';
